/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as DashboardPaymentIndexImport } from './routes/dashboard/payment/index'
import { Route as DashboardOrdersIndexImport } from './routes/dashboard/orders/index'
import { Route as DashboardOrderRoundIndexImport } from './routes/dashboard/orderRound/index'
import { Route as DashboardCustomersIndexImport } from './routes/dashboard/customers/index'
import { Route as DashboardBreadsIndexImport } from './routes/dashboard/breads/index'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardPaymentIndexRoute = DashboardPaymentIndexImport.update({
  id: '/payment/',
  path: '/payment/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardOrdersIndexRoute = DashboardOrdersIndexImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardOrderRoundIndexRoute = DashboardOrderRoundIndexImport.update({
  id: '/orderRound/',
  path: '/orderRound/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardCustomersIndexRoute = DashboardCustomersIndexImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardBreadsIndexRoute = DashboardBreadsIndexImport.update({
  id: '/breads/',
  path: '/breads/',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/breads/': {
      id: '/dashboard/breads/'
      path: '/breads'
      fullPath: '/dashboard/breads'
      preLoaderRoute: typeof DashboardBreadsIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/customers/': {
      id: '/dashboard/customers/'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/orderRound/': {
      id: '/dashboard/orderRound/'
      path: '/orderRound'
      fullPath: '/dashboard/orderRound'
      preLoaderRoute: typeof DashboardOrderRoundIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/payment/': {
      id: '/dashboard/payment/'
      path: '/payment'
      fullPath: '/dashboard/payment'
      preLoaderRoute: typeof DashboardPaymentIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBreadsIndexRoute: typeof DashboardBreadsIndexRoute
  DashboardCustomersIndexRoute: typeof DashboardCustomersIndexRoute
  DashboardOrderRoundIndexRoute: typeof DashboardOrderRoundIndexRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
  DashboardPaymentIndexRoute: typeof DashboardPaymentIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBreadsIndexRoute: DashboardBreadsIndexRoute,
  DashboardCustomersIndexRoute: DashboardCustomersIndexRoute,
  DashboardOrderRoundIndexRoute: DashboardOrderRoundIndexRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardPaymentIndexRoute: DashboardPaymentIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/breads': typeof DashboardBreadsIndexRoute
  '/dashboard/customers': typeof DashboardCustomersIndexRoute
  '/dashboard/orderRound': typeof DashboardOrderRoundIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/payment': typeof DashboardPaymentIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/breads': typeof DashboardBreadsIndexRoute
  '/dashboard/customers': typeof DashboardCustomersIndexRoute
  '/dashboard/orderRound': typeof DashboardOrderRoundIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/payment': typeof DashboardPaymentIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/breads/': typeof DashboardBreadsIndexRoute
  '/dashboard/customers/': typeof DashboardCustomersIndexRoute
  '/dashboard/orderRound/': typeof DashboardOrderRoundIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/payment/': typeof DashboardPaymentIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/breads'
    | '/dashboard/customers'
    | '/dashboard/orderRound'
    | '/dashboard/orders'
    | '/dashboard/payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/breads'
    | '/dashboard/customers'
    | '/dashboard/orderRound'
    | '/dashboard/orders'
    | '/dashboard/payment'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/breads/'
    | '/dashboard/customers/'
    | '/dashboard/orderRound/'
    | '/dashboard/orders/'
    | '/dashboard/payment/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/",
        "/dashboard/breads/",
        "/dashboard/customers/",
        "/dashboard/orderRound/",
        "/dashboard/orders/",
        "/dashboard/payment/"
      ]
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/breads/": {
      "filePath": "dashboard/breads/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/customers/": {
      "filePath": "dashboard/customers/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/orderRound/": {
      "filePath": "dashboard/orderRound/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/orders/": {
      "filePath": "dashboard/orders/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/payment/": {
      "filePath": "dashboard/payment/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
