/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as JoinImport } from './routes/join'
import { Route as IndexImport } from './routes/index'
import { Route as CallbackKakaoImport } from './routes/callback.kakao'
import { Route as SubPageProductsImport } from './routes/_sub-page/products'
import { Route as SubPageOrderImport } from './routes/_sub-page/order'
import { Route as SubPageFaqImport } from './routes/_sub-page/faq'
import { Route as SubPageBrandImport } from './routes/_sub-page/brand'
import { Route as SubPageMypageIndexImport } from './routes/_sub-page/mypage/index'
import { Route as SubPageMypagePasswordIndexImport } from './routes/_sub-page/mypage/password/index'
import { Route as SubPageMypageInfoIndexImport } from './routes/_sub-page/mypage/info/index'
import { Route as SubPageMypageAddressIndexImport } from './routes/_sub-page/mypage/address/index'

// Create/Update Routes

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const JoinRoute = JoinImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CallbackKakaoRoute = CallbackKakaoImport.update({
  id: '/callback/kakao',
  path: '/callback/kakao',
  getParentRoute: () => rootRoute,
} as any)

const SubPageProductsRoute = SubPageProductsImport.update({
  id: '/_sub-page/products',
  path: '/products',
  getParentRoute: () => rootRoute,
} as any)

const SubPageOrderRoute = SubPageOrderImport.update({
  id: '/_sub-page/order',
  path: '/order',
  getParentRoute: () => rootRoute,
} as any)

const SubPageFaqRoute = SubPageFaqImport.update({
  id: '/_sub-page/faq',
  path: '/faq',
  getParentRoute: () => rootRoute,
} as any)

const SubPageBrandRoute = SubPageBrandImport.update({
  id: '/_sub-page/brand',
  path: '/brand',
  getParentRoute: () => rootRoute,
} as any)

const SubPageMypageIndexRoute = SubPageMypageIndexImport.update({
  id: '/_sub-page/mypage/',
  path: '/mypage/',
  getParentRoute: () => rootRoute,
} as any)

const SubPageMypagePasswordIndexRoute = SubPageMypagePasswordIndexImport.update(
  {
    id: '/_sub-page/mypage/password/',
    path: '/mypage/password/',
    getParentRoute: () => rootRoute,
  } as any,
)

const SubPageMypageInfoIndexRoute = SubPageMypageInfoIndexImport.update({
  id: '/_sub-page/mypage/info/',
  path: '/mypage/info/',
  getParentRoute: () => rootRoute,
} as any)

const SubPageMypageAddressIndexRoute = SubPageMypageAddressIndexImport.update({
  id: '/_sub-page/mypage/address/',
  path: '/mypage/address/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/brand': {
      id: '/_sub-page/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof SubPageBrandImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/faq': {
      id: '/_sub-page/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SubPageFaqImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/order': {
      id: '/_sub-page/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof SubPageOrderImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/products': {
      id: '/_sub-page/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof SubPageProductsImport
      parentRoute: typeof rootRoute
    }
    '/callback/kakao': {
      id: '/callback/kakao'
      path: '/callback/kakao'
      fullPath: '/callback/kakao'
      preLoaderRoute: typeof CallbackKakaoImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/mypage/': {
      id: '/_sub-page/mypage/'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof SubPageMypageIndexImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/mypage/address/': {
      id: '/_sub-page/mypage/address/'
      path: '/mypage/address'
      fullPath: '/mypage/address'
      preLoaderRoute: typeof SubPageMypageAddressIndexImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/mypage/info/': {
      id: '/_sub-page/mypage/info/'
      path: '/mypage/info'
      fullPath: '/mypage/info'
      preLoaderRoute: typeof SubPageMypageInfoIndexImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/mypage/password/': {
      id: '/_sub-page/mypage/password/'
      path: '/mypage/password'
      fullPath: '/mypage/password'
      preLoaderRoute: typeof SubPageMypagePasswordIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/brand': typeof SubPageBrandRoute
  '/faq': typeof SubPageFaqRoute
  '/order': typeof SubPageOrderRoute
  '/products': typeof SubPageProductsRoute
  '/callback/kakao': typeof CallbackKakaoRoute
  '/mypage': typeof SubPageMypageIndexRoute
  '/mypage/address': typeof SubPageMypageAddressIndexRoute
  '/mypage/info': typeof SubPageMypageInfoIndexRoute
  '/mypage/password': typeof SubPageMypagePasswordIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/brand': typeof SubPageBrandRoute
  '/faq': typeof SubPageFaqRoute
  '/order': typeof SubPageOrderRoute
  '/products': typeof SubPageProductsRoute
  '/callback/kakao': typeof CallbackKakaoRoute
  '/mypage': typeof SubPageMypageIndexRoute
  '/mypage/address': typeof SubPageMypageAddressIndexRoute
  '/mypage/info': typeof SubPageMypageInfoIndexRoute
  '/mypage/password': typeof SubPageMypagePasswordIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_sub-page/brand': typeof SubPageBrandRoute
  '/_sub-page/faq': typeof SubPageFaqRoute
  '/_sub-page/order': typeof SubPageOrderRoute
  '/_sub-page/products': typeof SubPageProductsRoute
  '/callback/kakao': typeof CallbackKakaoRoute
  '/_sub-page/mypage/': typeof SubPageMypageIndexRoute
  '/_sub-page/mypage/address/': typeof SubPageMypageAddressIndexRoute
  '/_sub-page/mypage/info/': typeof SubPageMypageInfoIndexRoute
  '/_sub-page/mypage/password/': typeof SubPageMypagePasswordIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/login'
    | '/logout'
    | '/brand'
    | '/faq'
    | '/order'
    | '/products'
    | '/callback/kakao'
    | '/mypage'
    | '/mypage/address'
    | '/mypage/info'
    | '/mypage/password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/login'
    | '/logout'
    | '/brand'
    | '/faq'
    | '/order'
    | '/products'
    | '/callback/kakao'
    | '/mypage'
    | '/mypage/address'
    | '/mypage/info'
    | '/mypage/password'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/login'
    | '/logout'
    | '/_sub-page/brand'
    | '/_sub-page/faq'
    | '/_sub-page/order'
    | '/_sub-page/products'
    | '/callback/kakao'
    | '/_sub-page/mypage/'
    | '/_sub-page/mypage/address/'
    | '/_sub-page/mypage/info/'
    | '/_sub-page/mypage/password/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SubPageBrandRoute: typeof SubPageBrandRoute
  SubPageFaqRoute: typeof SubPageFaqRoute
  SubPageOrderRoute: typeof SubPageOrderRoute
  SubPageProductsRoute: typeof SubPageProductsRoute
  CallbackKakaoRoute: typeof CallbackKakaoRoute
  SubPageMypageIndexRoute: typeof SubPageMypageIndexRoute
  SubPageMypageAddressIndexRoute: typeof SubPageMypageAddressIndexRoute
  SubPageMypageInfoIndexRoute: typeof SubPageMypageInfoIndexRoute
  SubPageMypagePasswordIndexRoute: typeof SubPageMypagePasswordIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SubPageBrandRoute: SubPageBrandRoute,
  SubPageFaqRoute: SubPageFaqRoute,
  SubPageOrderRoute: SubPageOrderRoute,
  SubPageProductsRoute: SubPageProductsRoute,
  CallbackKakaoRoute: CallbackKakaoRoute,
  SubPageMypageIndexRoute: SubPageMypageIndexRoute,
  SubPageMypageAddressIndexRoute: SubPageMypageAddressIndexRoute,
  SubPageMypageInfoIndexRoute: SubPageMypageInfoIndexRoute,
  SubPageMypagePasswordIndexRoute: SubPageMypagePasswordIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/join",
        "/login",
        "/logout",
        "/_sub-page/brand",
        "/_sub-page/faq",
        "/_sub-page/order",
        "/_sub-page/products",
        "/callback/kakao",
        "/_sub-page/mypage/",
        "/_sub-page/mypage/address/",
        "/_sub-page/mypage/info/",
        "/_sub-page/mypage/password/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/join": {
      "filePath": "join.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/_sub-page/brand": {
      "filePath": "_sub-page/brand.tsx"
    },
    "/_sub-page/faq": {
      "filePath": "_sub-page/faq.tsx"
    },
    "/_sub-page/order": {
      "filePath": "_sub-page/order.tsx"
    },
    "/_sub-page/products": {
      "filePath": "_sub-page/products.tsx"
    },
    "/callback/kakao": {
      "filePath": "callback.kakao.tsx"
    },
    "/_sub-page/mypage/": {
      "filePath": "_sub-page/mypage/index.tsx"
    },
    "/_sub-page/mypage/address/": {
      "filePath": "_sub-page/mypage/address/index.tsx"
    },
    "/_sub-page/mypage/info/": {
      "filePath": "_sub-page/mypage/info/index.tsx"
    },
    "/_sub-page/mypage/password/": {
      "filePath": "_sub-page/mypage/password/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
