/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as JoinImport } from './routes/join'
import { Route as IndexImport } from './routes/index'
import { Route as CallbackKakaoImport } from './routes/callback.kakao'
import { Route as SubPageProductsImport } from './routes/_sub-page/products'
import { Route as SubPageFaqImport } from './routes/_sub-page/faq'
import { Route as SubPageBrandImport } from './routes/_sub-page/brand'
import { Route as SubPageOrderRoundIndexImport } from './routes/_sub-page/order-round/index'
import { Route as SubPageMypageIndexImport } from './routes/_sub-page/mypage/index'
import { Route as SubPageOrderRoundOrderRoundNoImport } from './routes/_sub-page/order-round/$orderRoundNo'
import { Route as SubPageMypagePasswordIndexImport } from './routes/_sub-page/mypage/password/index'
import { Route as SubPageMypageOrderListIndexImport } from './routes/_sub-page/mypage/order-list/index'
import { Route as SubPageMypageInfoIndexImport } from './routes/_sub-page/mypage/info/index'
import { Route as SubPageMypageCouponIndexImport } from './routes/_sub-page/mypage/coupon/index'
import { Route as SubPageMypageAddressIndexImport } from './routes/_sub-page/mypage/address/index'
import { Route as SubPageGuestOrderListIndexImport } from './routes/_sub-page/guest/order-list/index'
import { Route as SubPageMypageOrderListOrderNoImport } from './routes/_sub-page/mypage/order-list/$orderNo'
import { Route as SubPageMypageOrderListOrderNoDeliveryImport } from './routes/_sub-page/mypage/order-list_/$orderNo/delivery'

// Create/Update Routes

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const JoinRoute = JoinImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CallbackKakaoRoute = CallbackKakaoImport.update({
  id: '/callback/kakao',
  path: '/callback/kakao',
  getParentRoute: () => rootRoute,
} as any)

const SubPageProductsRoute = SubPageProductsImport.update({
  id: '/_sub-page/products',
  path: '/products',
  getParentRoute: () => rootRoute,
} as any)

const SubPageFaqRoute = SubPageFaqImport.update({
  id: '/_sub-page/faq',
  path: '/faq',
  getParentRoute: () => rootRoute,
} as any)

const SubPageBrandRoute = SubPageBrandImport.update({
  id: '/_sub-page/brand',
  path: '/brand',
  getParentRoute: () => rootRoute,
} as any)

const SubPageOrderRoundIndexRoute = SubPageOrderRoundIndexImport.update({
  id: '/_sub-page/order-round/',
  path: '/order-round/',
  getParentRoute: () => rootRoute,
} as any)

const SubPageMypageIndexRoute = SubPageMypageIndexImport.update({
  id: '/_sub-page/mypage/',
  path: '/mypage/',
  getParentRoute: () => rootRoute,
} as any)

const SubPageOrderRoundOrderRoundNoRoute =
  SubPageOrderRoundOrderRoundNoImport.update({
    id: '/_sub-page/order-round/$orderRoundNo',
    path: '/order-round/$orderRoundNo',
    getParentRoute: () => rootRoute,
  } as any)

const SubPageMypagePasswordIndexRoute = SubPageMypagePasswordIndexImport.update(
  {
    id: '/_sub-page/mypage/password/',
    path: '/mypage/password/',
    getParentRoute: () => rootRoute,
  } as any,
)

const SubPageMypageOrderListIndexRoute =
  SubPageMypageOrderListIndexImport.update({
    id: '/_sub-page/mypage/order-list/',
    path: '/mypage/order-list/',
    getParentRoute: () => rootRoute,
  } as any)

const SubPageMypageInfoIndexRoute = SubPageMypageInfoIndexImport.update({
  id: '/_sub-page/mypage/info/',
  path: '/mypage/info/',
  getParentRoute: () => rootRoute,
} as any)

const SubPageMypageCouponIndexRoute = SubPageMypageCouponIndexImport.update({
  id: '/_sub-page/mypage/coupon/',
  path: '/mypage/coupon/',
  getParentRoute: () => rootRoute,
} as any)

const SubPageMypageAddressIndexRoute = SubPageMypageAddressIndexImport.update({
  id: '/_sub-page/mypage/address/',
  path: '/mypage/address/',
  getParentRoute: () => rootRoute,
} as any)

const SubPageGuestOrderListIndexRoute = SubPageGuestOrderListIndexImport.update(
  {
    id: '/_sub-page/guest/order-list/',
    path: '/guest/order-list/',
    getParentRoute: () => rootRoute,
  } as any,
)

const SubPageMypageOrderListOrderNoRoute =
  SubPageMypageOrderListOrderNoImport.update({
    id: '/_sub-page/mypage/order-list/$orderNo',
    path: '/mypage/order-list/$orderNo',
    getParentRoute: () => rootRoute,
  } as any)

const SubPageMypageOrderListOrderNoDeliveryRoute =
  SubPageMypageOrderListOrderNoDeliveryImport.update({
    id: '/_sub-page/mypage/order-list_/$orderNo/delivery',
    path: '/mypage/order-list/$orderNo/delivery',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/brand': {
      id: '/_sub-page/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof SubPageBrandImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/faq': {
      id: '/_sub-page/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SubPageFaqImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/products': {
      id: '/_sub-page/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof SubPageProductsImport
      parentRoute: typeof rootRoute
    }
    '/callback/kakao': {
      id: '/callback/kakao'
      path: '/callback/kakao'
      fullPath: '/callback/kakao'
      preLoaderRoute: typeof CallbackKakaoImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/order-round/$orderRoundNo': {
      id: '/_sub-page/order-round/$orderRoundNo'
      path: '/order-round/$orderRoundNo'
      fullPath: '/order-round/$orderRoundNo'
      preLoaderRoute: typeof SubPageOrderRoundOrderRoundNoImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/mypage/': {
      id: '/_sub-page/mypage/'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof SubPageMypageIndexImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/order-round/': {
      id: '/_sub-page/order-round/'
      path: '/order-round'
      fullPath: '/order-round'
      preLoaderRoute: typeof SubPageOrderRoundIndexImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/mypage/order-list/$orderNo': {
      id: '/_sub-page/mypage/order-list/$orderNo'
      path: '/mypage/order-list/$orderNo'
      fullPath: '/mypage/order-list/$orderNo'
      preLoaderRoute: typeof SubPageMypageOrderListOrderNoImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/guest/order-list/': {
      id: '/_sub-page/guest/order-list/'
      path: '/guest/order-list'
      fullPath: '/guest/order-list'
      preLoaderRoute: typeof SubPageGuestOrderListIndexImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/mypage/address/': {
      id: '/_sub-page/mypage/address/'
      path: '/mypage/address'
      fullPath: '/mypage/address'
      preLoaderRoute: typeof SubPageMypageAddressIndexImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/mypage/coupon/': {
      id: '/_sub-page/mypage/coupon/'
      path: '/mypage/coupon'
      fullPath: '/mypage/coupon'
      preLoaderRoute: typeof SubPageMypageCouponIndexImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/mypage/info/': {
      id: '/_sub-page/mypage/info/'
      path: '/mypage/info'
      fullPath: '/mypage/info'
      preLoaderRoute: typeof SubPageMypageInfoIndexImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/mypage/order-list/': {
      id: '/_sub-page/mypage/order-list/'
      path: '/mypage/order-list'
      fullPath: '/mypage/order-list'
      preLoaderRoute: typeof SubPageMypageOrderListIndexImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/mypage/password/': {
      id: '/_sub-page/mypage/password/'
      path: '/mypage/password'
      fullPath: '/mypage/password'
      preLoaderRoute: typeof SubPageMypagePasswordIndexImport
      parentRoute: typeof rootRoute
    }
    '/_sub-page/mypage/order-list_/$orderNo/delivery': {
      id: '/_sub-page/mypage/order-list_/$orderNo/delivery'
      path: '/mypage/order-list/$orderNo/delivery'
      fullPath: '/mypage/order-list/$orderNo/delivery'
      preLoaderRoute: typeof SubPageMypageOrderListOrderNoDeliveryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/brand': typeof SubPageBrandRoute
  '/faq': typeof SubPageFaqRoute
  '/products': typeof SubPageProductsRoute
  '/callback/kakao': typeof CallbackKakaoRoute
  '/order-round/$orderRoundNo': typeof SubPageOrderRoundOrderRoundNoRoute
  '/mypage': typeof SubPageMypageIndexRoute
  '/order-round': typeof SubPageOrderRoundIndexRoute
  '/mypage/order-list/$orderNo': typeof SubPageMypageOrderListOrderNoRoute
  '/guest/order-list': typeof SubPageGuestOrderListIndexRoute
  '/mypage/address': typeof SubPageMypageAddressIndexRoute
  '/mypage/coupon': typeof SubPageMypageCouponIndexRoute
  '/mypage/info': typeof SubPageMypageInfoIndexRoute
  '/mypage/order-list': typeof SubPageMypageOrderListIndexRoute
  '/mypage/password': typeof SubPageMypagePasswordIndexRoute
  '/mypage/order-list/$orderNo/delivery': typeof SubPageMypageOrderListOrderNoDeliveryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/brand': typeof SubPageBrandRoute
  '/faq': typeof SubPageFaqRoute
  '/products': typeof SubPageProductsRoute
  '/callback/kakao': typeof CallbackKakaoRoute
  '/order-round/$orderRoundNo': typeof SubPageOrderRoundOrderRoundNoRoute
  '/mypage': typeof SubPageMypageIndexRoute
  '/order-round': typeof SubPageOrderRoundIndexRoute
  '/mypage/order-list/$orderNo': typeof SubPageMypageOrderListOrderNoRoute
  '/guest/order-list': typeof SubPageGuestOrderListIndexRoute
  '/mypage/address': typeof SubPageMypageAddressIndexRoute
  '/mypage/coupon': typeof SubPageMypageCouponIndexRoute
  '/mypage/info': typeof SubPageMypageInfoIndexRoute
  '/mypage/order-list': typeof SubPageMypageOrderListIndexRoute
  '/mypage/password': typeof SubPageMypagePasswordIndexRoute
  '/mypage/order-list/$orderNo/delivery': typeof SubPageMypageOrderListOrderNoDeliveryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_sub-page/brand': typeof SubPageBrandRoute
  '/_sub-page/faq': typeof SubPageFaqRoute
  '/_sub-page/products': typeof SubPageProductsRoute
  '/callback/kakao': typeof CallbackKakaoRoute
  '/_sub-page/order-round/$orderRoundNo': typeof SubPageOrderRoundOrderRoundNoRoute
  '/_sub-page/mypage/': typeof SubPageMypageIndexRoute
  '/_sub-page/order-round/': typeof SubPageOrderRoundIndexRoute
  '/_sub-page/mypage/order-list/$orderNo': typeof SubPageMypageOrderListOrderNoRoute
  '/_sub-page/guest/order-list/': typeof SubPageGuestOrderListIndexRoute
  '/_sub-page/mypage/address/': typeof SubPageMypageAddressIndexRoute
  '/_sub-page/mypage/coupon/': typeof SubPageMypageCouponIndexRoute
  '/_sub-page/mypage/info/': typeof SubPageMypageInfoIndexRoute
  '/_sub-page/mypage/order-list/': typeof SubPageMypageOrderListIndexRoute
  '/_sub-page/mypage/password/': typeof SubPageMypagePasswordIndexRoute
  '/_sub-page/mypage/order-list_/$orderNo/delivery': typeof SubPageMypageOrderListOrderNoDeliveryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/login'
    | '/logout'
    | '/brand'
    | '/faq'
    | '/products'
    | '/callback/kakao'
    | '/order-round/$orderRoundNo'
    | '/mypage'
    | '/order-round'
    | '/mypage/order-list/$orderNo'
    | '/guest/order-list'
    | '/mypage/address'
    | '/mypage/coupon'
    | '/mypage/info'
    | '/mypage/order-list'
    | '/mypage/password'
    | '/mypage/order-list/$orderNo/delivery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/login'
    | '/logout'
    | '/brand'
    | '/faq'
    | '/products'
    | '/callback/kakao'
    | '/order-round/$orderRoundNo'
    | '/mypage'
    | '/order-round'
    | '/mypage/order-list/$orderNo'
    | '/guest/order-list'
    | '/mypage/address'
    | '/mypage/coupon'
    | '/mypage/info'
    | '/mypage/order-list'
    | '/mypage/password'
    | '/mypage/order-list/$orderNo/delivery'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/login'
    | '/logout'
    | '/_sub-page/brand'
    | '/_sub-page/faq'
    | '/_sub-page/products'
    | '/callback/kakao'
    | '/_sub-page/order-round/$orderRoundNo'
    | '/_sub-page/mypage/'
    | '/_sub-page/order-round/'
    | '/_sub-page/mypage/order-list/$orderNo'
    | '/_sub-page/guest/order-list/'
    | '/_sub-page/mypage/address/'
    | '/_sub-page/mypage/coupon/'
    | '/_sub-page/mypage/info/'
    | '/_sub-page/mypage/order-list/'
    | '/_sub-page/mypage/password/'
    | '/_sub-page/mypage/order-list_/$orderNo/delivery'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SubPageBrandRoute: typeof SubPageBrandRoute
  SubPageFaqRoute: typeof SubPageFaqRoute
  SubPageProductsRoute: typeof SubPageProductsRoute
  CallbackKakaoRoute: typeof CallbackKakaoRoute
  SubPageOrderRoundOrderRoundNoRoute: typeof SubPageOrderRoundOrderRoundNoRoute
  SubPageMypageIndexRoute: typeof SubPageMypageIndexRoute
  SubPageOrderRoundIndexRoute: typeof SubPageOrderRoundIndexRoute
  SubPageMypageOrderListOrderNoRoute: typeof SubPageMypageOrderListOrderNoRoute
  SubPageGuestOrderListIndexRoute: typeof SubPageGuestOrderListIndexRoute
  SubPageMypageAddressIndexRoute: typeof SubPageMypageAddressIndexRoute
  SubPageMypageCouponIndexRoute: typeof SubPageMypageCouponIndexRoute
  SubPageMypageInfoIndexRoute: typeof SubPageMypageInfoIndexRoute
  SubPageMypageOrderListIndexRoute: typeof SubPageMypageOrderListIndexRoute
  SubPageMypagePasswordIndexRoute: typeof SubPageMypagePasswordIndexRoute
  SubPageMypageOrderListOrderNoDeliveryRoute: typeof SubPageMypageOrderListOrderNoDeliveryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SubPageBrandRoute: SubPageBrandRoute,
  SubPageFaqRoute: SubPageFaqRoute,
  SubPageProductsRoute: SubPageProductsRoute,
  CallbackKakaoRoute: CallbackKakaoRoute,
  SubPageOrderRoundOrderRoundNoRoute: SubPageOrderRoundOrderRoundNoRoute,
  SubPageMypageIndexRoute: SubPageMypageIndexRoute,
  SubPageOrderRoundIndexRoute: SubPageOrderRoundIndexRoute,
  SubPageMypageOrderListOrderNoRoute: SubPageMypageOrderListOrderNoRoute,
  SubPageGuestOrderListIndexRoute: SubPageGuestOrderListIndexRoute,
  SubPageMypageAddressIndexRoute: SubPageMypageAddressIndexRoute,
  SubPageMypageCouponIndexRoute: SubPageMypageCouponIndexRoute,
  SubPageMypageInfoIndexRoute: SubPageMypageInfoIndexRoute,
  SubPageMypageOrderListIndexRoute: SubPageMypageOrderListIndexRoute,
  SubPageMypagePasswordIndexRoute: SubPageMypagePasswordIndexRoute,
  SubPageMypageOrderListOrderNoDeliveryRoute:
    SubPageMypageOrderListOrderNoDeliveryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/join",
        "/login",
        "/logout",
        "/_sub-page/brand",
        "/_sub-page/faq",
        "/_sub-page/products",
        "/callback/kakao",
        "/_sub-page/order-round/$orderRoundNo",
        "/_sub-page/mypage/",
        "/_sub-page/order-round/",
        "/_sub-page/mypage/order-list/$orderNo",
        "/_sub-page/guest/order-list/",
        "/_sub-page/mypage/address/",
        "/_sub-page/mypage/coupon/",
        "/_sub-page/mypage/info/",
        "/_sub-page/mypage/order-list/",
        "/_sub-page/mypage/password/",
        "/_sub-page/mypage/order-list_/$orderNo/delivery"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/join": {
      "filePath": "join.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/_sub-page/brand": {
      "filePath": "_sub-page/brand.tsx"
    },
    "/_sub-page/faq": {
      "filePath": "_sub-page/faq.tsx"
    },
    "/_sub-page/products": {
      "filePath": "_sub-page/products.tsx"
    },
    "/callback/kakao": {
      "filePath": "callback.kakao.tsx"
    },
    "/_sub-page/order-round/$orderRoundNo": {
      "filePath": "_sub-page/order-round/$orderRoundNo.tsx"
    },
    "/_sub-page/mypage/": {
      "filePath": "_sub-page/mypage/index.tsx"
    },
    "/_sub-page/order-round/": {
      "filePath": "_sub-page/order-round/index.tsx"
    },
    "/_sub-page/mypage/order-list/$orderNo": {
      "filePath": "_sub-page/mypage/order-list/$orderNo.tsx"
    },
    "/_sub-page/guest/order-list/": {
      "filePath": "_sub-page/guest/order-list/index.tsx"
    },
    "/_sub-page/mypage/address/": {
      "filePath": "_sub-page/mypage/address/index.tsx"
    },
    "/_sub-page/mypage/coupon/": {
      "filePath": "_sub-page/mypage/coupon/index.tsx"
    },
    "/_sub-page/mypage/info/": {
      "filePath": "_sub-page/mypage/info/index.tsx"
    },
    "/_sub-page/mypage/order-list/": {
      "filePath": "_sub-page/mypage/order-list/index.tsx"
    },
    "/_sub-page/mypage/password/": {
      "filePath": "_sub-page/mypage/password/index.tsx"
    },
    "/_sub-page/mypage/order-list_/$orderNo/delivery": {
      "filePath": "_sub-page/mypage/order-list_/$orderNo/delivery.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
